# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dgst < Formula
  desc "Compute and print message digest hash values of stdin."
  homepage "https://github.com/maerics/dgst"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maerics/dgst/releases/download/v0.0.7/dgst_v0.0.7_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5a04cc3fc2453138160cd7dd8f90a6f5e0e7b947d528cfab94dc385fe0f93661"

      def install
        bin.install "dgst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maerics/dgst/releases/download/v0.0.7/dgst_v0.0.7_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6a7fecb9a16ab5f3f9ef732b348c9efc3a8db489d61011396aefa9cb3e511107"

      def install
        bin.install "dgst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/dgst/releases/download/v0.0.7/dgst_v0.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9ab4f39bb858b42fd95ab119f42d7999fdd134d9bcb0e2a16eebba01fec52bbb"

      def install
        bin.install "dgst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maerics/dgst/releases/download/v0.0.7/dgst_v0.0.7_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "14f84af8b550439b965418f5390a8aa935bc4d72e615be9b3fe84cdbf2135a2f"

      def install
        bin.install "dgst"
      end
    end
  end
end
