# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dgst < Formula
  desc "Compute and print message digest hash values of stdin."
  homepage "https://github.com/maerics/dgst"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/dgst/releases/download/v0.1.2/dgst_v0.1.2_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "80048a48de4f6e888c2a304a92be869819ba124e7cfd240f3cc6359db34996bc"

      def install
        bin.install "dgst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/dgst/releases/download/v0.1.2/dgst_v0.1.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d59bccf8cb6899bc7ff0bc35fa1a63a6d2e2f265317e8d83727658fed3f1c6fe"

      def install
        bin.install "dgst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/dgst/releases/download/v0.1.2/dgst_v0.1.2_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "ce673f468207e2b4e06f6ac867ba3dc6450e23efbf5ccbf6178318ed51c3acc0"

        def install
          bin.install "dgst"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/dgst/releases/download/v0.1.2/dgst_v0.1.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "f732469ef53c1406b27cc26a85b9030a1722b2d4b6fe04da301830238f9e8afc"

        def install
          bin.install "dgst"
        end
      end
    end
  end
end
