# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnslookup < Formula
  desc "Resolve DNS records for a host and print them as JSON or YAML."
  homepage "https://github.com/maerics/dnslookup"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/dnslookup/releases/download/v0.1.0/dnslookup_v0.1.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "87b221ee5ae36a86b32275c4bdacec926c1faff04541694048f099ac3de1a653"

      def install
        bin.install "dnslookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/dnslookup/releases/download/v0.1.0/dnslookup_v0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fc7bce632e84e5ac7f9af792e59b1af79b6582feadc352827d597a0283586946"

      def install
        bin.install "dnslookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/dnslookup/releases/download/v0.1.0/dnslookup_v0.1.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d1acd094cd04c0ff71af8f4b93224d3e7cb58df98a21387641c55f04d5a544cb"
      def install
        bin.install "dnslookup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/dnslookup/releases/download/v0.1.0/dnslookup_v0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "208bebe975680ab6ef6048bcf2486d48f17ed0d9bd843b43d3205bf41abbcfcd"
      def install
        bin.install "dnslookup"
      end
    end
  end
end
