# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enc < Formula
  desc "Transcode various formats between stdin and stdout."
  homepage "https://github.com/maerics/enc"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/enc/releases/download/v0.5.2/enc_v0.5.2_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "1cf2958451e41077eb0e639b4fd1ccd48a0ec790ec4dc45ecfc996c2dda4efeb"

      def install
        bin.install "enc"
        bin.install_symlink "enc" => "dec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/enc/releases/download/v0.5.2/enc_v0.5.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c0ae279ac2869a74f4ca58f0b9fe6159a036d02a366fba5613e6e5961ba879cf"

      def install
        bin.install "enc"
        bin.install_symlink "enc" => "dec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/enc/releases/download/v0.5.2/enc_v0.5.2_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "f1cef6141e3c49a03f2672e64a7fc9953cb3eef09ab0e753f0615a8ef8e737d3"

        def install
          bin.install "enc"
          bin.install_symlink "enc" => "dec"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/enc/releases/download/v0.5.2/enc_v0.5.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ea81f37af48fe8e5ec8bfd9298bb6191f9a0d70f3e8538abad3a7a84b7e8362b"

        def install
          bin.install "enc"
          bin.install_symlink "enc" => "dec"
        end
      end
    end
  end
end
