# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enc < Formula
  desc "Transcode various formats between stdin and stdout."
  homepage "https://github.com/maerics/enc"
  version "0.4.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/enc/releases/download/v0.4.7/enc_v0.4.7_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "25170a672d9647b4a083b5251823b004cc46ef7c2258fcd1ee4b6beb4acc0822"

      def install
        bin.install "enc"
        bin.install_symlink "enc" => "dec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/enc/releases/download/v0.4.7/enc_v0.4.7_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fc0d6b35ad60d78cce644f8a3562fd407bde5baf732082f6c870e5b3df3b7fb5"

      def install
        bin.install "enc"
        bin.install_symlink "enc" => "dec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/enc/releases/download/v0.4.7/enc_v0.4.7_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "efe742692b0abc818a0770efd68b63de348f39e6f289edac4d9a78ab7f1c9f69"

        def install
          bin.install "enc"
          bin.install_symlink "enc" => "dec"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maerics/enc/releases/download/v0.4.7/enc_v0.4.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "bb9999b6a4abd39d184362b4c424843ac6d175d77894971289441936b2ce9169"

        def install
          bin.install "enc"
          bin.install_symlink "enc" => "dec"
        end
      end
    end
  end
end
