# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pass < Formula
  desc "Password hashing and key derivation utilities."
  homepage "https://github.com/maerics/pass"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/pass/releases/download/v0.2.0/pass_v0.2.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "71406523fc435eebf297e413be52241350e2af30c86204283c4f2e45a2fb9fc0"

      def install
        bin.install "pass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/pass/releases/download/v0.2.0/pass_v0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b04590ac758d82340f824bee461eb0c77efc36c62562d750f38cc7998b475d39"

      def install
        bin.install "pass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/pass/releases/download/v0.2.0/pass_v0.2.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "baec9eb9848e0f4395f6e30e18524b223f330d8914782cfb5698dbd1de32c956"
      def install
        bin.install "pass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/pass/releases/download/v0.2.0/pass_v0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3c9983a4f602d686a06c870a3acdaf2ce0f0e31d31d480a7ae5ffd4c240317ae"
      def install
        bin.install "pass"
      end
    end
  end
end
