# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pass < Formula
  desc "Transcode various formats between stdin and stdout."
  homepage "https://github.com/maerics/pass"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maerics/pass/releases/download/v0.1.0/pass_v0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8bb4905877593f1a3cb24912510846049a6a360217e9727b1fef9608176eddba"

      def install
        bin.install "pass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maerics/pass/releases/download/v0.1.0/pass_v0.1.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e22cb6f6b9afed86ffbde04c8cc7cfefe8ee23388252be432f2df91200d122b9"

      def install
        bin.install "pass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/pass/releases/download/v0.1.0/pass_v0.1.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c633334399d97f342c64afbaa12ff61e8fa8b793587f72e8fc91a890b6a5a3d9"

      def install
        bin.install "pass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/pass/releases/download/v0.1.0/pass_v0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e06ecc1bca0e5c9c90cce5acb7280ff523504130df93d3b2a3bb4d1ebe600564"

      def install
        bin.install "pass"
      end
    end
  end
end
