# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rand < Formula
  desc "Print random bytes from a secure source to stdout."
  homepage "https://github.com/maerics/rand"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/rand/releases/download/v0.2.0/rand_v0.2.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "423ddc9437112dad50c35edcfbc37aa78bc0a1bdb40962d08c3e9eec7720c108"

      def install
        bin.install "rand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/rand/releases/download/v0.2.0/rand_v0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f4ab46830d0767ccb413075e5ae72b3fd1d822d1f7774fd92fb64ad9dd026abe"

      def install
        bin.install "rand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/rand/releases/download/v0.2.0/rand_v0.2.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c93b794103f08998c5123e65505b1afc8d9dc0fac37cf35339b870bf23ba8de"
      def install
        bin.install "rand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/rand/releases/download/v0.2.0/rand_v0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4e72c0ac47c9a12771ea6948d2708556cc7a467a660406c55fc063835878f4cf"
      def install
        bin.install "rand"
      end
    end
  end
end
