# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rand < Formula
  desc "Print random bytes from a secure source to stdout."
  homepage "https://github.com/maerics/rand"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/maerics/rand/releases/download/v0.1.0/rand_v0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "81267bbaf4fb2c511c2c22bd9e1caf6f3dd43013864fbdd6ea805a351c49c17a"

      def install
        bin.install "rand"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/maerics/rand/releases/download/v0.1.0/rand_v0.1.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "34102bec22f215f4ee413306473805ec97225812d1737fba6004e5cad78db041"

      def install
        bin.install "rand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/rand/releases/download/v0.1.0/rand_v0.1.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2df0403e0404fc7140a25f5bafc16de6221635592a710205bec308fe14c12c88"

      def install
        bin.install "rand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/rand/releases/download/v0.1.0/rand_v0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f16a306dd7cc12484a5058ad83b7d068c6ccd193184488abc9369a9c60bc8ae9"

      def install
        bin.install "rand"
      end
    end
  end
end
