# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Url < Formula
  desc "Parse URLs and print structured data in JSON and YAML."
  homepage "https://github.com/maerics/url"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maerics/url/releases/download/v0.2.0/url_v0.2.0_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e8935c265d2fd66c79a7597fffe16ae71b711b452abdc55348eff76f5a5f77d5"

      def install
        bin.install "url"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maerics/url/releases/download/v0.2.0/url_v0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4c1d8b99ec136fc01dc81d8edaf7e0d0c32b486221a4ca0bd657d3dd0538c599"

      def install
        bin.install "url"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/url/releases/download/v0.2.0/url_v0.2.0_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b04c17c7e9a812d6839221c943fdb2dd63174569740e69a1374753e1343dca63"
      def install
        bin.install "url"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maerics/url/releases/download/v0.2.0/url_v0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "37bc4c702ef463c0142e1fd38536550b443496b37c38ea732ef186a4727408fb"
      def install
        bin.install "url"
      end
    end
  end
end
